add docker

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -68,8 +68,17 @@ jobs:
       - name: 🛠️ Build Docker Image
         run: |
           cd MLProject
-          RUN_PATH=$(ls -td mlruns/0/*/ | head -n 1)
+          echo "🔍 Searching for latest MLflow run..."
+          RUN_PATH=$(ls -td mlruns/0/*/ | grep -v datasets | head -n 1)
+          echo "✅ Found run path: $RUN_PATH"
+          if [ ! -d "$RUN_PATH/artifacts/model" ]; then
+            echo "❌ Model folder not found at $RUN_PATH/artifacts/model"
+            echo "Available structure:"
+            ls -R mlruns/
+            exit 1
+          fi
           mlflow models build-docker --model-uri "$RUN_PATH/artifacts/model" --name "workflow-ci"
+
       - name: 🏷️ Tag Docker Image
         run: |
           docker tag workflow-ci ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
