Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,16 +56,20 @@ jobs:
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           echo "Latest run ID: $RUN_ID"
 
-      - name: Upload to GitHub LFS
+      - name: Upload MLflow artifacts to Git LFS
         run: |
-          git config --global user.name ${{ secrets.username }}
-          git config --global user.email ${{ secrets.email }}
-          git lfs install
-          git add -f MLProject/mlruns/
-          git commit -m "Upload MLFlow with Github LFS" || true
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
-          git push origin main
-          echo "Upload MLFlow with Github LFS"
+          if [ -d "MLProject/mlruns" ]; then
+            git config --global user.name "${{ secrets.username }}"
+            git config --global user.email "${{ secrets.email }}"
+            git lfs install
+            git add -f MLProject/mlruns/
+            git commit -m "Upload MLflow artifacts" || echo "No changes to commit"
+            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+            git push origin main || echo "Nothing pushed"
+          else
+           echo "MLruns folder not found. Skipping LFS upload."
+          fi
+
 
       - name: Build Docker Model
         run: |
